
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.dani96.analizadores.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SIGNO_MAS = 18;
  public static final int PARENTESIS_ABIERTO = 24;
  public static final int CADENA = 17;
  public static final int DECIMAL = 31;
  public static final int ETIQUETAS = 9;
  public static final int CORCHETE_CERRADO = 27;
  public static final int DOS_PUNTOS = 22;
  public static final int TIPO = 12;
  public static final int PORCENTAJE = 14;
  public static final int SIGNO_DIVISION = 21;
  public static final int BARRAS = 3;
  public static final int VALORES = 10;
  public static final int LLAVE_ABIERTA = 28;
  public static final int PARENTESIS_CERRADO = 25;
  public static final int COMA = 5;
  public static final int SIGNO_POR = 20;
  public static final int EOF = 0;
  public static final int TOTAL = 15;
  public static final int DEF = 2;
  public static final int PIE = 4;
  public static final int SIGNO_MENOS = 19;
  public static final int EXTRA = 16;
  public static final int CANTIDAD = 13;
  public static final int error = 1;
  public static final int PUNTO_COMA = 23;
  public static final int EJEY = 8;
  public static final int EJEX = 7;
  public static final int ENTERO = 30;
  public static final int LLAVE_CERRADA = 29;
  public static final int CORCHETE_ABIERTO = 26;
  public static final int UNIR = 11;
  public static final int TITULO = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "COMA",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "CANTIDAD",
  "PORCENTAJE",
  "TOTAL",
  "EXTRA",
  "CADENA",
  "SIGNO_MAS",
  "SIGNO_MENOS",
  "SIGNO_POR",
  "SIGNO_DIVISION",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "ENTERO",
  "DECIMAL"
  };
}

